### ISSUE TITLE
'first', 'last' stopped working after update?

### ISSUE THREAD

**Issue by JTreehorn** [emmt/CartesianBoxes.jl#1]
This previously returned an index, now doesn't work... any clue?

thanks for the package.

```
julia> test = CartesianBox(CartesianIndex(1,1),CartesianIndex(6,6))
CartesianBox{2}((1:6, 1:6))

julia> test.first
ERROR: type CartesianBox has no field first
Stacktrace:
 [1] getproperty(x::CartesianBox{2, CartesianIndices{2, Tuple{UnitRange{Int64}, UnitRange{Int64}}}}, f::Symbol)
   @ Base ./Base.jl:33
 [2] top-level scope
   @ none:1
```

**Comment by emmt** [comment]
You should use `first(test)` not `test.first` because the former relyies on the API (with some guarantees of being maintained plus `first`, `last` etc. are rather standard methods) while the latter depends on how `CartesianBox` are represented internally (which has just changed with version 0.2 of `CartesianBoxes` in order to improve portability with the evolution of Julia).

**Comment by JTreehorn** [comment]
OK thanks. & yes other accesses test[1], test[end] certainly work.
